import type { ContactViewModel, FactSource, RawContact, RawInteraction, QualificationFact, InteractionViewModel } from '@/types/contact';

export const parseDate = (value: unknown): Date | null => {
  if (typeof value === 'number') return new Date(value < 10_000_000_000 ? value * 1000 : value);
  if (typeof value !== 'string' || !value.trim()) return null;
  const match = value.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\s+(\d{1,2}):(\d{2}))?/);
  if (match) return new Date(Number(match[3]), Number(match[2]) - 1, Number(match[1]), Number(match[4] || 0), Number(match[5] || 0));
  const iso = new Date(value); return Number.isNaN(iso.getTime()) ? null : iso;
};
export const dateValue = (value: unknown) => parseDate(value)?.getTime() ?? 0;
export const formatDate = (value: unknown) => { const date = parseDate(value); return date ? new Intl.DateTimeFormat('es-ES', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(date) : null; };
export const normalizePhone = (value: unknown) => { if (typeof value !== 'string') return ''; const digits = value.replace(/\D/g, ''); if (digits.startsWith('0034')) return digits.slice(4); if (digits.startsWith('34') && digits.length === 11) return digits.slice(2); return digits; };
export const displayPhone = (value: string | null) => { const local = normalizePhone(value); if (!local) return null; return local.length === 9 ? `+34 ${local.slice(0, 3)} ${local.slice(3, 6)} ${local.slice(6)}` : value?.trim() || local; };
export const humanize = (key: string) => key.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/[_-]+/g, ' ').replace(/^./, x => x.toUpperCase());
const originMap: Record<string, string> = { VOICE_CALL: 'Llamada', VOICE: 'Llamada', VOZ: 'Llamada', llamada: 'Llamada', WHATSAPP: 'WhatsApp', whatsapp: 'WhatsApp', WEBSITE: 'Web', WEB_FORM: 'Formulario web', META_LEAD_ADS: 'Meta Ads', WITEI: 'Witei', CRM: 'CRM' };
const channelMap: Record<string, string> = { VOICE: 'Llamada', WHATSAPP: 'WhatsApp', WEB_FORM: 'Formulario', EMAIL: 'Email' };
const sourceInfo = (source: unknown, sourceRef: unknown): [FactSource, string] => { const s = String(source || '').toLowerCase(); const ref = String(sourceRef || '').toLowerCase(); if (s === 'manual' || s === 'human') return ['human', 'Editado por una persona']; if (ref.includes('import')) return ['import', 'Importado']; if (s === 'explicit' || s === 'ai' || s === 'inferred') return ['ai', 'Detectado por IA']; return ['unknown', source ? String(source) : 'Procedencia desconocida']; };
const parseQualification = (value: unknown): Record<string, any> => { if (typeof value === 'string') { try { return parseQualification(JSON.parse(value)); } catch { return {}; } } return value && typeof value === 'object' ? value as Record<string, any> : {}; };
export const formatValue = (value: unknown): string => { if (value === true) return 'Sí'; if (value === false) return 'No'; if (value == null) return '—'; if (Array.isArray(value)) return value.map(formatValue).join(', '); if (typeof value === 'object') return Object.entries(value as Record<string, unknown>).map(([k, v]) => `${humanize(k)}: ${formatValue(v)}`).join(' · '); return String(value); };
function normalizeFacts(raw: unknown): Record<string, QualificationFact[]> { const parsed = parseQualification(raw); const hasWrapper = parsed.qualification && typeof parsed.qualification === 'object'; const groups = hasWrapper ? parsed.qualification as Record<string, unknown> : parsed; const result: Record<string, QualificationFact[]> = {}; const addFacts = (group: string, fields: unknown) => { if (group.startsWith('_') || !fields || typeof fields !== 'object') return; const facts: QualificationFact[] = []; for (const [key, rawFact] of Object.entries(fields as Record<string, unknown>)) { const fact = rawFact && typeof rawFact === 'object' && 'value' in rawFact ? rawFact as Record<string, any> : { value: rawFact }; const [source, sourceLabel] = sourceInfo(fact.source, fact.sourceRef); facts.push({ key, label: humanize(key), value: fact.value, source, sourceLabel, date: formatDate(fact.updatedAt), sourceRef: fact.sourceRef || null }); } if (facts.length) result[group] = facts; }; for (const [group, fields] of Object.entries(groups)) addFacts(group, fields); if (hasWrapper) { const extras = Object.entries(parsed).filter(([key]) => key !== 'qualification' && !key.startsWith('_')); if (extras.length) result.other = extras.map(([key, value]) => { const fact = value && typeof value === 'object' && 'value' in value ? value as Record<string, any> : { value }; const [source, sourceLabel] = sourceInfo(fact.source, fact.sourceRef); return { key, label: humanize(key), value: fact.value, source, sourceLabel, date: formatDate(fact.updatedAt), sourceRef: fact.sourceRef || null }; }); } return result; }
function normalizeInteraction(item: RawInteraction): InteractionViewModel { const channel = String(item.channel || 'OTHER').toUpperCase(); return { id: item.id, channel, channelLabel: channelMap[channel] || humanize(channel), direction: item.direction || 'unknown', date: formatDate(item.created_at), dateValue: dateValue(item.created_at), content: item.content || 'Sin contenido registrado', transcript: typeof item.metadata?.transcript_excerpt === 'string' ? item.metadata.transcript_excerpt : null }; }
export function normalizeContact(raw: RawContact): ContactViewModel { const originalName = raw.full_name?.trim(); const phone = displayPhone(raw.phone || null); const email = raw.email?.trim() || null; const name = originalName ? originalName.replace(/\s+/g, ' ').split(' ').map(word => word ? `${word[0].toUpperCase()}${word.slice(1).toLowerCase()}` : word).join(' ') : phone || email || 'Contacto sin nombre'; const initials = name === 'Contacto sin nombre' ? '?' : name.split(/\s+/).slice(0, 2).map(x => x[0]).join('').toUpperCase(); const interactions = (raw.interactions || []).map(normalizeInteraction).sort((a, b) => b.dateValue - a.dateValue); return { id: raw.id, organizationId: raw.organization_id || null, name, initials, phone, phoneDigits: normalizePhone(raw.phone), email, origin: String(raw.lead_source || 'UNKNOWN'), originLabel: originMap[String(raw.lead_source || '')] || humanize(String(raw.lead_source || 'Origen desconocido')), createdAt: formatDate(raw.created_at), createdValue: dateValue(raw.created_at), notes: raw.notes || null, tags: raw.tags || [], qualification: normalizeFacts(raw.qualification_data), interactions, compliance: { restricted: false, phoneBlocked: false, whatsappBlocked: false, reason: null }, duplicateOf: [] }; }
